### ISSUE TITLE
Enable Network Acceleration where possible

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-azure#549] opened 2020-04-20 16:27 UTC
/kind feature

**Describe the solution you'd like**
Enable Network Acceleration on VM instances where supported.

**Anything else you would like to add:**
This would require being able to determine if the requested instance type supports Network Acceleration as not all VM instance types support it.

**Comment by CecileRobertMichon** [comment] 2020-04-20 16:44
duplicate of #307 

/close

**Closed** 2020-04-20 16:44 UTC
Labels: kind/feature
