### ISSUE TITLE
Consider moving etcd to it's own storage device

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-azure#548] opened 2020-04-20 16:26 UTC
/kind feature

**Describe the solution you'd like**
Currently we deploy etcd on the OS disk for the VM instance. To avoid potential issues related to cached bandwidth/IOPS available on the VM, we should consider moving etcd to it's own storage device with cache configured for `None`.

Links providing a bit more context on disk throttling in Azure:
https://docs.microsoft.com/en-us/archive/blogs/xiangwu/azure-vm-storage-performance-and-throttling-demystify
https://docs.d2iq.com/mesosphere/dcos/1.13/installing/production/system-requirements/azure-recommendations/#disk-configurations

**Comment by devigned** [comment] 2020-04-20 16:45
I think this is a dup of https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/448

**Comment by CecileRobertMichon** [comment] 2020-04-20 16:45
duplicate of #448 

/close

**Comment by devigned** [comment] 2020-04-20 16:46
Great idea and something we should do sooner than later.

**Comment by CecileRobertMichon** [comment] 2020-04-20 16:46
it's in the current milestone :)

**Closed** 2020-04-20 16:45 UTC
Labels: kind/feature
