### ISSUE TITLE
BYO Azure VNet

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#314] opened 2019-10-22 21:50 UTC
/kind feature

A customer provides their own Azure VNet resource id, and CAPZ doesn't provision it's own VNet. Instead it uses the already created Azure VNet.

**Comment by justaugustus** [comment] 2019-10-24 20:46
Closed as duplicate of #178.
/close

**Comment by justaugustus** [comment] 2019-10-24 21:25
jk, reopening.
/assign @CecileRobertMichon 
/reopen
/milestone next
/priority important-soon

**Closed** 2020-01-09 20:00 UTC
Labels: kind/feature, priority/important-soon
