### ISSUE TITLE
machinepool webhook not a resource 

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#662] opened 2020-05-31 20:43 UTC
/kind bug

I used the quickstart to configure my env for Azure so I have a mgmt cluster which is an AKS cluster and a workload cluster in Azure. 

I ran `clusterctl config cluster capi-quickstart --kubernetes-version v1.17.4 --flavor machinepool > capi-quickstart.yaml ` and I expected my workload cluster config to be over written with the right machine pool config and then I used kubectl to apply the new configuration with `kubectl apply -f capi-quickstart.yaml.' 

The output was 
`cluster.cluster.x-k8s.io/capi-quickstart unchanged
azurecluster.infrastructure.cluster.x-k8s.io/capi-quickstart unchanged
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capi-quickstart-control-plane configured
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capi-quickstart-control-plane unchanged
azuremachinepool.exp.infrastructure.cluster.x-k8s.io/capi-quickstart-mp-0 created
kubeadmconfig.bootstrap.cluster.x-k8s.io/capi-quickstart-mp-0 created
Error from server (InternalError): error when creating "capi-quickstart.yaml": Internal error occurred: failed calling webhook "default.exp.machinepool.cluster.x-k8s.io": the server could not find the requested resource` 

**Anything else you would like to add:**
This is probably a documentation issue because I'm stumbling around trying to figure out when the machinepool resource should have been installed. 

**Environment:**

- cluster-api-provider-azure version: v0.4.4
 Kubernetes version: (use `kubectl version`): v1.17.4
- OS (e.g. from `/etc/os-release`):

**Comment by devigned** [comment] 2020-06-01 15:07
@rbitia did you turn on the experimental flags for the controllers. Check out [this slack thread](https://kubernetes.slack.com/archives/CEX9HENG7/p1589827095210000).

**Comment by CecileRobertMichon** [comment] 2020-06-01 16:32
https://github.com/kubernetes-sigs/cluster-api/issues/3073

**Comment by CecileRobertMichon** [comment] 2020-06-02 16:37
I'm going to close this since we confirmed there isn't a bug and the documentation gap is already being tracked in the issue above.

/close

**Closed** 2020-06-02 16:38 UTC
Labels: kind/bug
