### ISSUE TITLE
Make Standard LoadBalancer outbound connection timeout configurable

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#677] opened 2020-06-03 21:25 UTC
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Let's enable a convenient user-override for the cluster LoadBalancer outbound rule timeout, which governs how long to keep idle connections open. Certain applications may be idle by design for longer than 4 minutes (the default), and we want to accommodate that. Conversely, certain clusters may not have any such applications, but will expect a lot of aggregate outbound connections, in which case they will want to more aggressively close connections to better protect against SNAT port exhaustion.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment] 2020-06-03 21:36
duplicate of #676 

pasted your comment in the above issue

/close

**Closed** 2020-06-03 21:36 UTC
Labels: kind/feature
